### PR TITLE
deploy-20231011

### PR DESCRIPTION
**Pull request by FXF48-Mila**
Add the deployment information for deploy-29231004

### CODE REVIEW

**Comment by FXF48-Mila** [comment]
@ctuguinay  Hi Caesar, we have added two new audiomoths for this deployment. they are called "M" and "N". Could you add these two audiomoth names to PyTest? Thanks a lot.

**Comment by ctuguinay** [comment]
@FXF48-Mila I think this could be a good exercise for you since you're new to Pytest. Could you try to make the changes needed?

Here's a short tutorial on how to get started with Pytest: https://docs.pytest.org/en/7.4.x/getting-started.html#get-started. Try to see if you can get the tests running on your own IDE. Let me know if you have any questions.

**Comment by FXF48-Mila** [comment]
@ctuguinay Sure. I'll try my best. I would like to know where to find the PyTest file for this repo?

**Comment by ctuguinay** [comment]
@FXF48-Mila Should be in the scripts subdirectory.

**Comment by FXF48-Mila** [comment]
@aditya-uw Hi Aditya, I think you can now start adding deployment photos to this PR.

**Comment by FXF48-Mila** [comment]
I added the two new audiomoth names to PyTest.

**Comment by aditya-uw** [comment]
@ctuguinay Could you look over this and let me know if it looks good?

**Comment by ctuguinay** [comment]
Looks good to me @aditya-uw. Crazy how we're already at M and N 😭

**Pull request merged**
