### PR TITLE
Deploy 2023-07-05

### PR DESCRIPTION
**Pull request by m-ball3**
Deployment on 2023-07-05 PR includes the following:

CSV additions for 2023-07-05
Added field record pics for 2023-06-28 and 2023-07-05

Notes: 
Caesar double checked the config files on "mnt" to ensure the field records matched what the Audiomoths recorded. 
The pytest has been modified to include new Audiomoth H

### CODE REVIEW

**Comment by ctuguinay** [comment]
A few strange merge conflicts had to be resolved, but this looks good to me. @aditya-uw let me know what you think of this 😄

**Comment by aditya-uw** [comment]
@ctuguinay @m-ball3 looks good to me! 

Just curious, how has the weather been over the few weeks? Any notable changes? I encourage you to record under "Notes" if there are any changes like "Central Pond water level receding/rising" or "Bushes has been trimmed by UBNA management". There's nothing in specific I'm looking for but 6 months from now these field records will be our main record of what we observed during deployments. So feel free to be verbose :)

**Comment by aditya-uw** [comment]
Also, I forgot to ask a while ago, how are we recording LAT/LON currently? I remember Molly was going to explore iNaturalist. Just wanted to know if there were any updates on this. 

I recently observed Audiomoth deployments being done in Bangalore where I am and the deployer used WhatsApp to send her location to her partner haha. My mind was blown.

**Comment by m-ball3** [comment]
> @ctuguinay @m-ball3 looks good to me!
> 
> Just curious, how has the weather been over the few weeks? Any notable changes? I encourage you to record under "Notes" if there are any changes like "Central Pond water level receding/rising" or "Bushes has been trimmed by UBNA management". There's nothing in specific I'm looking for but 6 months from now these field records will be our main record of what we observed during deployments. So feel free to be verbose :)

Aditya, 
I will definitely be on the lookout for changes! The weather has been really pleasant (not too hot, not rainy), and I have not noticed significant recession/rising at Central Pond as of yet. I also have not noticed if someone has gone in to trim any of the bushes, but now I will keep extra care to take notice. Thank you for the tip!(:

**Comment by aditya-uw** [comment]
I see @m-ball3! Thank you for answering! Feel free to merge this PR when you want!

**Comment by aditya-uw** [comment]
Wait a second, @ctuguinay I am looking at `recover-20230705/UBNA_006` and the file format seems to be different. Each file is labelled as starting from 9min into the 30-min span. Do you see this too and if so, do you know why?

**Comment by aditya-uw** [comment]
> Wait a second, @ctuguinay I am looking at `recover-20230705/UBNA_006` and the file format seems to be different. Each file is labelled as starting from 9min into the 30-min span. Do you see this too and if so, do you know why?

Oh I see, I think you changed the configuration as sunset/sunrise times changed?

**Comment by aditya-uw** [comment]
Also, if there were intentional changes, could you record these in our field records perhaps under notes? Just to say that there was a change in Audiomoth configuration for a reason.

**Pull request merged**
