### PR TITLE
Deploy 2023-09-13 PR

### PR DESCRIPTION
**Pull request by aditya-uw**
Hey @ctuguinay, I'll add the field records information shortly along with the images. Could you just review and make sure I added in everything? Thanks!

### CODE REVIEW

**Comment by aditya-uw** [comment]
Okay @ctuguinay sorry if I email-spammed you but I was able to fix the typos that caused the pytest haha. Take a look and let me know if it's good to merge!

**Review by ctuguinay — APPROVED** [review]
Looks good to me and feel free to squash and merge. Just curious why there's a seemingly large gap between TF and Foliage. @aditya-uw

**Comment by aditya-uw** [comment]
Oh we did Telephone Field, E-18 Bridge, Central Pond, Foliage in that order

**Comment by ctuguinay** [comment]
Oh I see gotcha

**Pull request merged**
