### PR TITLE
deploy-20231026

### PR DESCRIPTION
**Pull request by FXF48-Mila**
Add the field records for audiomoths that are recovered on 20231026.

### CODE REVIEW

**Comment by aditya-uw** [comment]
Hi Mila this looks good! Just one thing, can you change 'CT' to 'AK' for Scribe? Just so we know it was just you and me out in the field.

**Comment by FXF48-Mila** [comment]
Hi @aditya-uw, I fixed the scribe for the deployment this time. But I wonder should I fix the scribe for the previous deployments also?

**Comment by aditya-uw** [comment]
@FXF48-Mila Yeah for recover-20231026 make it AK. For recover-20231018, I don't remember. You can try and change all of the CT October rows because I know Caesar was not with us for these.

**Comment by aditya-uw** [comment]
I think you can say recover-20231018, recover-20231011, and recover-20231004 it was MB (Mollie).

**Comment by aditya-uw** [comment]
Oh @FXF48-Mila, sorry, I meant you should only change scribe if it is 'CT' during October. Can you undo your changes if you changed anything else?

**Comment by FXF48-Mila** [comment]
Hi @aditya-uw, I only change the scribe from "CT" to "AK", "MS", or "MB" since the October 11th deployment. The principle of my change is that if the deployer is you, the scribe at all times except 20231011 is Mollie is me. If deployer is me then the scribe at that time is you. Is that okay?

**Comment by aditya-uw** [comment]
Ohhh I see, I'm good with this @FXF48-Mila! Thank you for explaining! I think we are good to Squash and Merge! Do that when you are ready!

**Comment by leewujung** [comment]
@aditya-uw @FXF48-Mila : This is why you should always **fill in** the information and **not copy-past**e from the previous row, because this way you are forced to think about what should be in each field and put it in. 🙂 Imagine trying to correct this info 2 months from now -- it will be very difficult and likely includes errors.

**Comment by FXF48-Mila** [comment]
@leewujung I will be sure to be careful when filling in all the information in the future instead of copying and pasting.

**Comment by leewujung** [comment]
Sounds good!

**Pull request merged**
