### PR TITLE
Deploy-20230920

### PR DESCRIPTION
**Pull request by aditya-uw**
Starting with:
- Recovery information added to deploy-20230913.
- Added in the notes of the missing Central Pond Audiomoths that the Audiomoths were lost in the field.
- Corrected typo and added YeonJoon as YJ in the deployer section for deploy-20230913 (need to correct to YC)

### CODE REVIEW

**Comment by aditya-uw** [comment]
Added deployment pictures; forgot to take picture of Foliage deployment (Audiomoth G)

**Comment by aditya-uw** [comment]
@ctuguinay, I added in last week's deployment PR. Could you give it a look and let me know if it's good? I'll merge after.

**Comment by ctuguinay** [comment]
@aditya-uw We only have nighttime recorders now, so 4 recorders in total?

Also, this looks good to me. Feel free to squash and merge.

**Comment by aditya-uw** [comment]
@ctuguinay yeah but we should think about putting up a daytime recorder at Foliage or Central (or both). The 4 nighttime recorders last week was just improvisation to losing the 2 Central Pond recorders.

**Pull request merged**
