### PR TITLE
Updating the deployment guide + protocols to 2023 details

### PR DESCRIPTION
**Pull request by aditya-uw**
This addresses issue #77. 

To start:
- I had made some initial changes such as updating what we are bringing to the field and how we are checking voltages and such. 
- I deleted 'Updating Spreadsheet' because that was referring to updating the Google spreadsheet that I had initially made back in September 2021 to keep track of all the details.

Over the past few days, I incorporated:
- Wu-Jung's suggestion to remove "will be" from the note about the desktop apps.
- Wu-Jung's suggestion to change "study" to "record" when talking about why we are configuring Audiomoths with 192kHz.
- Fixed the numbering after that last numbered point.
- Wu-Jung's suggestion to change "to be able to check" to "to check"
- Wu-Jung's suggestion to elaborate on how we are blacking out the Audiomoth LED with electrical tape.
- Wu-Jung's suggestion to change "check the LEDs to check its status" to "check the LED status"
- Caesar's pytest tutorial in `protocol/01_lab.md`

There are still suggestions to commit and edits to make so I've only listed the changes made so far.

### CODE REVIEW

**Comment by aditya-uw** [comment]
@ctuguinay I reorganized the info in the pytest tutorial to avoid having one big bullet point. Does the new format look okay? I didn't remove info, I either elaborated or left as it was. Let me know if there's anything else I can add!

**Comment by ctuguinay** [comment]
@aditya-uw Nice! The Pytest part looks good to me. 👍

**Comment by aditya-uw** [comment]
Thanks! 

I'll keep this PR open to add deployment details pertaining to when we start using the recently delivered Audiomoths! These details will consist of having 6 Audiomoths prepared in-lab and simply swapping them out with the 6 Audiomoths previously deployed. Instead of only swapping batteries because before this recent delivery we only had 6 Audiomoths. Now that we have 16 Audiomoths, we are allowed to have 6 be kept in-lab while 6 are deployed.

**Comment by leewujung** [comment]
Hey @aditya-uw : how about merging this and have the new section added in as a separate PR later? Small PRs are usually better since it makes reviewing it easier. Also for the title, how about adding 2023 in there for future reference?

**Comment by aditya-uw** [comment]
Sounds good @leewujung! That makes sense, I'll squash and merge this then? (you can leave a thumbs up)

**Pull request merged**
